version: "3.7"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-code
    hostname: php-code
    ports:
        - "80:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql
    networks: 
      - code-network

  php:
    build:
      context: ./php
    container_name: php-code
    hostname: php-code
    volumes:
      - ./code:/code
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks: 
      - code-network

  mysql:
    image: mysql:5.7.28
    container_name: mysql-code
    hostname: mysql-code
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: ecodb
       MYSQL_USER: eco
       MYSQL_PASSWORD: password
    networks:
      - code-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-code
    hostname: phpmyadmin-code
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      MYSQL_USER: eco
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password 
    links:
      - mysql
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    networks:
      - code-network

volumes:
  db_data: {}

networks:
  code-network:
    driver: bridge